{
 "title": "Kdb+ Plugin Demo",
 "time": { "from": "2020-12-10T00:00:00.000Z", "to": "2020-12-16T23:59:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "targetsym",
    "query": "exec distinct sym from statictab"
   },
   { "name": "columns", "query": "cols statictab" },
   { "name": "buckets", "query": "1,2,5,10,20,30,60" }
  ]
 },
 "panels": [
  {
   "title": "Sym Volatility - ${targetsym}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Volatility" }
   ],
   "targets": [
    {
     "conflationDefaultAggType": "dev",
     "conflationDuration": "${buckets}",
     "conflationDurationMS": 300000000000,
     "conflationUnit": "m",
     "groupingField": "sym",
     "kdbSideFunction": "Select Function",
     "panelType": "graph",
     "queryError": {
      "error": [
       false,
       false,
       false,
       false
      ],
      "message": [
       "",
       "",
       "",
       ""
      ]
     },
     "queryId": "4DIySmxB",
     "rowCountLimit": 10000,
     "select": [
      [
       { "datatype": "f", "params": [ "price" ], "type": "column" }
      ]
     ],
     "table": "statictab",
     "version": "1.0.1",
     "where": [
      {
       "datatype": "s",
       "name": "",
       "params": [
        "sym",
        "=",
        "`${targetsym}"
       ],
       "type": "expression"
      }
     ]
    }
   ]
  },
  {
   "title": "Average ${columns} - ${targetsym}",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "conflationDefaultAggType": "avg",
     "conflationDuration": "${buckets}",
     "conflationDurationMS": 300000000000,
     "conflationUnit": "m",
     "groupingField": "sym",
     "kdbSideFunction": "Select Function",
     "panelType": "marcusolsson-hourly-heatmap-panel",
     "queryError": {
      "error": [
       false,
       false,
       false,
       false
      ],
      "message": [
       "",
       "",
       "",
       ""
      ]
     },
     "queryId": "4e1fBpvH",
     "rowCountLimit": 10000,
     "select": [
      [
       { "datatype": "f", "params": [ "${columns}" ], "type": "column" }
      ]
     ],
     "table": "statictab",
     "version": "1.0.1",
     "where": [
      {
       "datatype": "s",
       "name": "",
       "params": [
        "sym",
        "=",
        "`${targetsym}"
       ],
       "type": "expression"
      }
     ]
    }
   ]
  },
  {
   "title": "Profit and Loss - ${targetsym}",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "conflationDefaultAggType": "avg",
     "conflationDuration": "5",
     "conflationDurationMS": 300000000000,
     "conflationUnit": "m",
     "funcTimeCol": "time",
     "kdbFunction": "select time, price, bid, ask, side, position, pnl, tot_pnl:sums pnl from pnl where sym=`${targetsym}",
     "kdbSideFunction": "Select Function",
     "panelType": "table",
     "queryError": {
      "error": [
       false,
       false,
       false,
       false
      ],
      "message": [
       "",
       "",
       "",
       ""
      ]
     },
     "queryId": "taI512e4",
     "rowCountLimit": 10000,
     "select": [
      [
       { "params": [ "value" ], "type": "column" }
      ]
     ],
     "version": "1.0.1"
    }
   ]
  }
 ]
}